name: app_router
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  collection: ^1.15.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
