name: app_router
description: A new Flutter package project.
version: 0.0.1
homepage: "none"

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
